#!/bin/bash

if [[ "$1" = "enp4s0f0" && "$2" = "up" ]]; then
  /sbin/ethtool -G enp4s0f1 rx 4096 tx 4096
fi

if [[ "$1" = "enp4s0f1" && "$2" = "up" ]]; then
  /sbin/ethtool -G enp4s0f1 rx 4096 tx 4096
fi
