---
- name: Applying Netplan Configuration
  command: netplan apply
  listen: netplan apply config
  become: true
  when: netplan_apply

- name: restart dnsmasq
  service: name=dnsmasq state=restarted enabled=yes
