---
- name: Install Firewalld
  apt: name=firewalld state=present

# Port Forwarding
- sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present

# Firewall Rules

- firewalld:
    zone: external
    interface: "{{external_interface}}"
    permanent: true
    state: enabled

- firewalld:
    zone: internal
    interface: "{{internal_interface}}"
    permanent: true
    state: enabled

- firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: external

- firewalld:
    zone: internal
    service: dhcp
    permanent: true
    state: enabled

- firewalld:
    zone: internal
    service: dns
    permanent: true
    state: enabled

- firewalld:
    zone: internal
    port: 9000/tcp
    permanent: true
    state: enabled
