---
- name: Install Firewalld
  apt: name=firewalld state=present

# Port Forwarding
- sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present

# Firewall Rules

- name: Set External (Egress) interface to External
  ansible.posix.firewalld:
    zone: external
    interface: "{{external_interface}}"
    permanent: yes
    state: enabled

- name: Set Internal interface to Internal
  ansible.posix.firewalld:
    zone: internal
    interface: "{{internal_interface}}"
    permanent: yes
    state: enabled

- name: Enable Masquerade
  ansible.posix.firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    zone: external

- name: Open DHCP access internally
  ansible.posix.firewalld:
    zone: internal
    service: dhcp
    permanent: yes
    state: enabled

- name: Open DMS access internally
  ansible.posix.firewalld:
    zone: internal
    service: dns
    permanent: yes
    state: enabled

- name: Open Portainer access internally
  ansible.posix.firewalld:
    zone: internal
    port: 9000/tcp
    permanent: yes
    state: enabled
