---
- name: Install LLDP daemon
  apt: name=lldpd state=present

- name: Make sure lldpd is started, and is enabled on restart.
  service: name=lldpd state=started enabled=yes

- name: Install the chrony daemon to synchronize the clocks to ms.
  apt: name=chrony

- name: Make sure chrony is started, and is enabled on restart.
  service: name=chrony state=started enabled=yes

- name: Make sure ntp is stopped and disabled.
  service: name=ntp state=stopped enabled=no
