---
- name: Install LLDP daemon
  apt: name=lldpd state=present

- name: Make sure lldpd is started, and is enabled on restart.
  service: name=lldpd state=started enabled=yes

- name: Install the NTP daemon to synchronize the clocks to ms.
  apt: name=ntp

- name: Make sure ntp is started, and is enabled on restart.
  service: name=ntp state=started enabled=yes
