---
- name: Install docker
  apt: name=docker.io state=present

- name: Install python3-pip
  apt: name=python3-pip state=present

- name: Install docker python package
  pip:
    name: docker

- name: "Deploy Portainer to {{ inventory_hostname }}"
  docker_container:
    name: portainer
    image: "portainer/portainer:latest"
    state: started
    detach: true
    recreate: false
    restart_policy: "always"
    published_ports: "10.0.1.1:9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/portainer:/data"
  register: portainer_docker

- name: "Deploy Etcd3 to {{ inventory_hostname }}"
  docker_container:
    name: etcd3
    image: "bitnami/etcd:latest"
    state: started
    detach: true
    recreate: false
    restart_policy: "always"
    published_ports: ["10.0.1.1:2379:2379", "10.0.1.1:2380:2380"]
    env:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "etcd.eandersson.net:2379"
  register: etcd3_docker
